server:
  port: 9006
spring:
  application:
    name: tensquare_spit  # 指定服务名。
  data:
    mongodb:
      host: 192.168.33.128
      port: 27017
      database: spitdb
  redis:
    host: 192.168.33.128
